name: Go

on: [push]
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.15.x, 1.16.x, 1.17.x, 1.18.x, 1.19.x]
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout
      uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: Get deps
      run: go get ./...
    - name: Linter
      run: |
        gofmt -d -s .
        go vet *.go
    - name: Tests
      run:  |
        go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...
        bash <(curl -s https://codecov.io/bash) || true
